services:
  mysql:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: elliot
      MYSQL_USER: elliot
      MYSQL_PASSWORD: elliot
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: elliot
    restart: unless-stopped
  
  checkid:
    image: jorgearguello/checkid:2.1.0-compumax
    ports:
      - "5050:8000"
    restart: unless-stopped
  
volumes:
  mysql_data: {}