# Generated by Django 5.1.7 on 2025-03-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_datosbiometricos_incidencias_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=255)),
                ('id_registro_afectado', models.IntegerField()),
                ('datos_antiguos', models.TextField()),
                ('datos_nuevos', models.TextField()),
                ('fecha_hora', models.DateField()),
                ('ip_usuario', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id_justificante', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FileField(upload_to='')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_carga', models.DateField()),
                ('id_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.incidencias')),
            ],
        ),
    ]
