# Generated by Django 5.1.7 on 2025-03-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auditoria_justificante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_entrada', models.IntegerField()),
                ('tolerancia_salida', models.IntegerField()),
                ('dias_laborables', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIR', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sabado'), ('DOM', 'Domingo')], max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=255)),
                ('longitud', models.CharField(max_length=255)),
                ('radio_geo_permitido', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoHorario',
            fields=[
                ('id_empleado_horario', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.empleado')),
                ('id_horario', models.ManyToManyField(related_name='Empleado', to='attendance.horario')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.sede')),
            ],
        ),
    ]
