# Generated by Django 5.1.7 on 2025-03-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_horario_sede_empleadohorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_registro', models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida')], max_length=3)),
                ('fecha_hora', models.DateField()),
                ('imagen_verificacion', models.ImageField(upload_to='')),
                ('confianza_reconocimiento', models.FloatField()),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('permitido', models.BooleanField()),
                ('ip_dispositivo', models.CharField(max_length=20)),
                ('dispositivo_info', models.TextField()),
                ('estatus', models.CharField(choices=[('VAL', 'Valido'), ('FUP', 'Fuera de perimetro'), ('RET', 'Retrasado'), ('MAN', 'Manual'), ('SOS', 'Sospechoso')], max_length=3)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.empleado')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.sede')),
            ],
        ),
    ]
