# Generated by Django 5.1.7 on 2025-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_registroasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='imagen_verificacion',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
